In [1]:
import torch

In [7]:
a = torch.tensor([2., 3.], requires_grad=True)
b = torch.tensor([6., 4.], requires_grad=True)

In [8]:
Q = 3*a**3 - b**2

In [9]:
Q

tensor([-12.,  65.], grad_fn=<SubBackward0>)

In [10]:
a.grad, b.grad

(None, None)

In [11]:
external_grad = torch.tensor([1., 1.])
Q.backward(gradient=external_grad)

In [12]:
a.grad, b.grad

(tensor([36., 81.]), tensor([-12.,  -8.]))

In [13]:
print(9*a**2 == a.grad)
print(-2*b == b.grad)

tensor([True, True])
tensor([True, True])
