In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n{x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}\n")

Ones Tensor: 
tensor([[1, 1],
        [1, 1]])

Random Tensor:
tensor([[0.1943, 0.0676],
        [0.3829, 0.8812]])



In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}\n")
print(f"Ones Tensor:\n{ones_tensor}\n")
print(f"Zeros Tensor:\n{zeros_tensor}\n")

Random Tensor:
tensor([[0.1039, 0.3664, 0.7205],
        [0.7962, 0.5429, 0.7032]])

Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [6]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [9]:
tensor = torch.tensor(data)
tensor

tensor([[1, 2],
        [3, 4]])

In [8]:
tensor[0]

tensor([1, 2])

In [10]:
tensor[:, 0]

tensor([1, 3])

In [11]:
tensor[..., -1]

tensor([2, 4])

In [12]:
tensor[:, 1] = 0
tensor

tensor([[1, 0],
        [3, 0]])

In [13]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1, 0],
        [3, 0]]) 

tensor([[6, 5],
        [8, 5]])


In [15]:
print(tensor, "\n")
tensor = tensor + 5
print(tensor)

tensor([[6, 5],
        [8, 5]]) 

tensor([[11, 10],
        [13, 10]])


In [16]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [17]:
# tensor, np.array -> 메모리 공유...?
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
